name: 'Hello World'
description: 'Greet someone'
inputs:
  target-models:  
    description: 'What to includ'
    required: true
    default: 'cvms'
outputs:
  build-log:
    description: "build log"
    value: ${{ steps.random-number-generator.outputs.build-log }}
runs:
  using: "composite"
  steps:
    - run: echo Hello from UCVM/toPython3 action.yml ${{ inputs.target-models }}.
      shell: bash
    - run: pwd
      shell: bash
    - run: ls
      shell: bash
    - id: build
      run: echo "::set-output name=build-log::$(echo $RANDOM)"
      shell: bash
    - run: |
         echo ${{ github.action_path }}
         ls ${{ github.action_path }}/../..
      shell: bash
    - name: set UCVM_SRC_PATH,UCVM_INSTALL_PATH 
      run:  |
         echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/UCVMC" >> $GITHUB_ENV
         echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/TARGET" >> $GITHUB_ENV
      shell: bash
    - run: |
         export MYPATH=${{ github.action_path }}
         echo $MYPATH
      shell: bash
    - run: |
       export UCVM_INSTALL_PATH=${{ github.action_path }}/../../TARGET
       env $UCVM_INSTALL_PATH
      shell: bash
    - run: env $GITHUB_ENV
      shell: bash

