name: 'Hello World'
description: 'Greet someone'
inputs:
  target-models:  
    description: 'What to includ'
    required: true
    default: 'cvms'
outputs:
  build-log:
    description: "build log"
    value: ${{ steps.random-number-generator.outputs.build-log }}
runs:
  using: "composite"
  steps:
    - run: echo Hello from UCVM/toPython3 action.yml ${{ inputs.target-models }}.
      shell: bash
    - run: ( echo " pwd =>"; pwd;
             echo " RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " github.action_path =>"${{ github.action_path }};)
      shell: bash
    - run: ( /bin/mkdir $RUNNER_WORKSPACE/TARGET;
             /bin/ln -s ${{ github.action_path }}/../.. $RUNNER_WORKSPACE/UCVM;
             ls $RUNNER_WORKSPACE)
      shell: bash
    - id: build
      run: echo "::set-output name=build-log::$(cat ucvm_setup_install.log)"
      shell: bash
    - run: ( echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/UCVM" >> $GITHUB_ENV;
             echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/TARGET" >> $GITHUB_ENV)
      shell: bash
    - run: env
      shell: bash
  
