name: 'Hello World'
description: 'Greet someone'
inputs:
  target-models:  
    description: 'What to includ'
    required: true
    default: 'cvms'
outputs:
  build-log:
    description: "build log"
    value: ${{ steps.random-number-generator.outputs.build-log }}
runs:
  using: "composite"
  steps:
    - run: echo Hello from UCVM/toPython3 action.yml ${{ inputs.target-models }}.
      shell: bash
    - run: pwd
      shell: bash
    - run: /bin/mkdir ucvmSpace ucvmSpace/TARGET 
      shell: bash
    - run: /bin/ln -s ${{ github.action_path }}/../.. ucvmSpace/UCVM 
      shell: bash
    - id: build
      run: echo "::set-output name=build-log::$(echo $RANDOM)"
      shell: bash
    - run: |
      echo " RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE
      echo " github.action_path =>"${{ github.action_path }}
      ls $RUNNER_WORKSPACE/*/ucvmSpace
      shell: bash
    - run: |
        echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm_plotting/ucvmSpace/UCVM" >> $GITHUB_ENV
        echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/ucvm_plotting/ucvmSpace/TARGET" >> $GITHUB_ENV
      shell: bash
    - run: env
      shell: bash
  
