name: 'Hello World'
description: 'Greet someone'
inputs:
  target-models:  
    description: 'What to includ'
    required: true
    default: 'cvms'
outputs:
  build-log:
    description: "build log"
    value: ${{ steps.random-number-generator.outputs.build-log }}
runs:
  using: "composite"
  steps:
    - run: echo Hello from UCVM/toPython3 action.yml ${{ inputs.target-models }}.
      shell: bash
    - run: pwd
      shell: bash
    - run: mkdir ucvmSPACE 
      cd ucvmSPACE
      ln -s ${{ github.action_path }}/../.. UCVMC
      cd ..
      shell: bash
    - id: build
      run: echo "::set-output name=build-log::$(echo $RANDOM)"
      shell: bash
    - run: |
         echo ${{ github.action_path }}
         ls ${{ github.action_path }}/../..
      shell: bash
    - run: echo $RUNNER_WORKSPACE
      shell: bash
    - run: echo ${{ github.action_path }}
      shell: bash

