
name: 'action to build ucvm from remote request'
description: 'invoked from ucvm models or ucvm_plotting'
inputs:
  initiating-repo :
    description: 'Which repository did the request came from'
    required: false
    default: 'ucvm_plotting'
  target-model:  
    description: 'Which cvm to include'
    required: false
    default: 'none'
outputs:
    build-log:
    description: 'return log for ucvm_setup.py'
    value: ${{ steps.post-build-log.outputs.log-file }}
runs:
  using: "composite"
  steps:
    - id: greeting
      run: echo Hello from ucvm's action.yml initiated from  ${{ inputs.initiating-repo }}
      shell: bash
    - id: show_env
      run: ( echo " pwd =>"; pwd;
             echo " UCVM_SRC_PATH =>"$UCVM_SRC_PATH;
             echo " UCVM_INSTALL_PATH =>"$UCVM_INSTALL_PATH;
             echo " RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " github.action_path =>"${{ github.action_path }};)
      shell: bash
    - id: build_ucvm 
      if: ${{ inputs.target-model != 'none' }}
      run: (cd $UCVM_SRC_PATH; ./.github/scripts/ucvm-build-${{ inputs.target-model }}.sh)
      shell: bash
   - id: post-build-log
      run: echo "::set-output name=log-file::$(echo $UCVM_SRC_PATH/ucvm_setup_install.log)"
      shell: bash
#

#    - name: test_ucvm
#      run: (cd $UCVM_SRC_PATH; ./.github/scripts/ucvm-test.sh)
#      shell: bash
     

  
