name: 'Hello World from UCVM'
description: 'invoked from ucvm_plotting'
inputs:
  target-models:  
    description: 'Which cvm to include'
    required: true
    default: 'cvms'
outputs:
  build-log:
    description: "build log"
    value: ${{ steps.post-build.outputs.build-log }}
runs:
  using: "composite"
  steps:
    - run: echo Hello from UCVM/toPython3 action.yml ${{ inputs.target-models }}.
      shell: bash
    - run: ( echo " pwd =>"; pwd;
             echo " RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " github.action_path =>"${{ github.action_path }};)
      shell: bash
    - run: ( /bin/mkdir $RUNNER_WORKSPACE/TARGET;
             /bin/ln -s ${{ github.action_path }}/../.. $RUNNER_WORKSPACE/UCVM;
             ls $RUNNER_WORKSPACE)
      shell: bash
    - run: ( echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/UCVM" >> $GITHUB_ENV;
             echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/TARGET" >> $GITHUB_ENV)
      shell: bash
    - name: build ucvm with cvmh
      run: (cd $UCVM_SRC_PATH; ./.github/scripts/ucvm-build-cvmh.sh)
      shell: bash
    - name: run ucvm tests
      run: (cd $UCVM_SRC_PATH; ./.github/scripts/ucvm-test.sh)
      shell: bash
    - id: post-build
      run: echo "::set-output name=build-log::$(cat $RUNNER_WORKSPACE/UCVM/ucvm_setup_install.log)"
      shell: bash
    - name: ucvm_query
      run: (which ucvm_query; ucvm_query -H; which python; python -V)
      shell: bash
    - name: install and run ucvm_plotting
      run: (cd $RUNNER_WORKSPACE/ucvm_plotting; ./unpack-dist)
      shell: bash

  
