
name: 'action to build ucvm from remote request'
description: 'invoked from ucvm_plotting'
inputs:
  target-models:  
    description: 'Which cvm to include'
    required: true
    default: 'cvms'
outputs:
  build-log:
    description: "return log for ucvm_setup.py"
    value: ${{ steps.post-build-log.outputs.log-file }}
runs:
  using: "composite"
  steps:
    - run: echo Hello from ucvm/toPython3 action.yml ${{ inputs.target-models }}.
      shell: bash
    - run: ( echo " pwd =>"; pwd;
             echo " RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " github.action_path =>"${{ github.action_path }};)
      shell: bash
    - run: ( /bin/ln -s ${{ github.action_path }}/../.. $RUNNER_WORKSPACE/ucvm;
             ls $RUNNER_WORKSPACE)
      shell: bash
    - run: ( echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV;
             echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV)
      shell: bash
    - name: build ucvm with cvmh
      run: (cd $UCVM_SRC_PATH; ./.github/scripts/ucvm-build-cvmh.sh)
      shell: bash
    - id: post-build-log
      run: echo "::set-output name=log-file::$(echo $RANDOM)"
      shell: bash
    - name: build ucvm with cvmh
      run: (cd $UCVM_SRC_PATH; ./.github/scripts/ucvm-test.sh)
      shell: bash
#    - run: pwd
#      shell: bash
#    - run: env
#      shell: bash

  
