name: ucvm-build-cvmh-py2
  ucvm-build-cvmh-py2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7.16]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV

    - name: checkout ucvm
      uses: actions/checkout@v2
      with:
        ref: main

    - name: build ucvm with cvms and cvmh
      run: ./.github/scripts/ucvm-build-cvms-cvmh.sh
      shell: bash

