name: ucvm-build-cvmh-py3
  ucvm-build-cvmh-py3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/UCVMC" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/TARGET" >> $GITHUB_ENV
    - name: checkout ucvm toPython3
      uses: actions/checkout@v2
      with: 
        ref: toPython3
    - name: build ucvm with cvms and cvmh
      run: ./.github/scripts/ucvm-build-cvms-cvmh.sh
      shell: bash

