name: ucvm-ci

on:
  push:
    branches: [ target ]

jobs:
  ucvm-build-cvmh:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
<<<<<<< HEAD
    - name: checkout ucvm target
      uses: actions/checkout@v2
      with: 
        ref: target
=======
    - uses: actions/checkout@v2
>>>>>>> main
    - name: build ucvm with cvmh
      run: ./.github/scripts/ucvm-build-cvmh.sh 
      shell: bash
    - name: test ucvm with cvmh
      run: ./.github/scripts/ucvm-test.sh
      shell: bash

  ucvm-build-cvms-cvmh:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
<<<<<<< HEAD
    - name: checkout ucvm target
      uses: actions/checkout@v2
      with: 
        ref: target
=======
    - name: checkout ucvm toPython3
      uses: actions/checkout@v2
>>>>>>> main
    - name: build ucvm with cvms and cvmh
      run: ./.github/scripts/ucvm-build-cvms-cvmh.sh
      shell: bash
    - name: test ucvm with cvms and cvmh
      run: ./.github/scripts/ucvm-test.sh
      shell: bash

  ucvm-build-albacore-lsu-wf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
    - name: checkout ucvm target
      uses: actions/checkout@v2
      with: 
        ref: target
    - name: build ucvm with albacore, cvlsu, ivlsu and wfcvm
      run: ./.github/scripts/run-build-albacore-lsu-wf.sh
      shell: bash
    - name: test ucvm with albacore, cvlsu, ivlsu and wfcvm
      run: ./.github/scripts/ucvm-test.sh
      shell: bash
