name: ucvm-ci

on:
  push:
    branches: [ toPython3 ]
  pull_request:
    branches: [ toPython3 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "{UCVM_SRC_PATH}=$RUNNER_WORKSPACE/UCVMC" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "{UCVM_INSTALL_PATH}=$RUNNER_WORKSPACE/UCVMC_TARGET" >> $GITHUB_ENV
    - name: set LD_LIBRARY_PATH 
      run: echo "{LD_LIBRARY_PATH}={$UCVM_INSTALL_PATH/lib/euclid3/lib:$UCVM_INSTALL_PATH/lib/proj-5/lib:$UCVM_INSTALL_PATH/model/cvms/lib:$UCVM_INSTALL_PATH/model/cvms5/lib:$UCVM_INSTALL_PATH/model/cvmh1511/lib}" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with: 
        ref: toPython3
    - name: build ucvm
      run: ./ci/runner-build.sh
      shell: bash
    - name: debug build
      run: ./ci/runner-debug.sh
      shell: bash
    - name: make check
      run: make runcheck
